$(document).ready(function(){
    $("div.mask").fadeOut(2000);
    $("div.button#kaka").click(function(){
        window.location.href="https://kaka.wetofu.top";
    });
    $("div.button#tonychyi").click(function(){
        window.location.href="https://tonychyi.wetofu.top";
    });
});
